server:
  port: 8089

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: suyehao
    password: syh1234567

mybatis:
  type-aliases-package: org.course.code
  mapper-locations:
    - mapper/*
